### PR TITLE
Ensure that we don't overlook errors in first PyObject_RichCompareBool call

### LINKED ISSUE #15: Tests break on Python 3.5
```
ValueError: incomparable                                                                                [0/1943]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/nix-build-python3.5-BTrees-4.1.4.drv-0/BTrees-4.1.4/BTrees/tests/testBTrees.py", line 426, in testF
oo
    t[DoesntLikeBeingCompared()] = None
  File "/tmp/nix-build-python3.5-BTrees-4.1.4.drv-0/BTrees-4.1.4/BTrees/tests/testBTrees.py", line 416, in __cmp
__
    raise ValueError('incomparable')
SystemError: <class 'ValueError'> returned a result with an error set

```

### PR DESCRIPTION
**Pull request by jimfulton**
Python 3.5 turns such cases into SystemErrors.

See: https://bugs.python.org/issue23571

Fixes #15.

### CODE REVIEW

**Comment by jimfulton** [comment]
@tseaver @jamadden Anyone want to review this?

**Comment by jamadden** [comment]
The actual change LGTM, in that it matches the discussion on #16. I guess it doesn't need an explicit test case? It looks like there were many failures of the test suite under 3.5 without the change, based on #15.

**Comment by tseaver** [comment]
Given that we are asserting Python 3.5 support in Trove / changelog, shouldn't this PR add it to `tox.ini` and `.travis.yml`?

**Comment by jamadden** [comment]
3.5 was added to travis.yml, but not tox.

**Comment by jimfulton** [comment]
I don't know this tox.ini. :) I assume it's obvious to add 3.5. I'll do so.

**Comment by tseaver** [comment]
@jimfulton WIthout `tox`, how are you ensuring that you don't break tests on a supported Python without first pushing?

**Comment by jimfulton** [comment]
I don't. I run manually on a Python 3 version and a Python 2 version.  I let Travis do the rest.  Sometimes, I may not have all of the versions available myself that travis has.

**Comment by jamadden** [comment]
@jimfulton Yes, it's pretty easy to add 3.5 to tox.ini. In the list of environments at the top of 'tox.ini', simply add a new entry 'py35' (boy that's a long list):
```diff
diff --git a/tox.ini b/tox.ini
index ab4e767..f56a1af 100644
--- a/tox.ini
+++ b/tox.ini
@@ -3,7 +3,7 @@ envlist =
 # Jython support pending 2.7 support, due 2012-07-15 or so.  See:
 # http://fwierzbicki.blogspot.com/2012/03/adconion-to-fund-jython-27.html
 #   py26,py27,py32,jython,pypy,coverage,docs
-    py26,py27,py27-pure,pypy,py32,py33,py34,pypy3,w_zodb,coverage,docs
+    py26,py27,py27-pure,pypy,py32,py33,py34,py35,pypy3,w_zodb,coverage,docs

 [testenv]
 deps =
```

Since I was already testing that locally, I *think* I can even commit it to this branch if you'd like me to.

**Comment by jimfulton** [comment]
Please do. Thanks.

**Comment by jamadden** [comment]
Done :)

**Comment by jimfulton** [comment]
Released as 4.2.0.

**Pull request merged**
