### PR TITLE
adds python 3.8 on macos to the travis build.

### PR DESCRIPTION
**Pull request by fgregg**
This should allow for making macos wheels for py3.8.

### CODE REVIEW

**Comment by fgregg** [comment]
thanks @mgedmin, could you trigger a pypi build. we shouldn't need to cut a new release.

**Comment by mgedmin** [comment]
> thanks @mgedmin, could you trigger a pypi build. we shouldn't need to cut a new release.

You should be able to do it too.  The procedure for building wheels is

- create new temporary git branch based on the release tag you want
- cherry-pick the .travis.yml (or appveyor) changes you want
- comment out all the jobs you don't want (builds for OSes/versions that already have wheels), basically just leave the one job you want
- comment out the condition that only git tags run this pypi upload job
- push the temporary git branch
- wait for Travis CI to build and upload the wheel
- delete the temporary git branch

**Comment by fgregg** [comment]
thanks! will do.

**Comment by fgregg** [comment]
Hi @mgedmin, I flubbed these instructions a bit by not starting by basing off the release tag, so I pushed a prelease version to pypi. https://pypi.org/project/BTrees/4.6.2.dev0/

Many apologies, let me know how you would like me to proceed.

**Comment by mgedmin** [comment]
Well, the good news is prereleases on PyPI are harmless, since pip install will ignore them.

I've deleted the bad release anyway.

**Comment by fgregg** [comment]
really sorry about this. I think I'm going to just wait until your next release.

**Comment by mgedmin** [comment]
I seriously doubt that anyone else even noticed a single MacOS-only binary wheel of a prerelease version that was available for a few hours only.  And hey, a valuable learning experience!

(I wish Travis CI would allow jobs to generate and make available for downloading artifacts, like Appveyor does.  Then one could build the wheels, test them, then upload them manually.)

**Pull request merged**
