### PR TITLE
Initial port to GitHub Actions

### PR DESCRIPTION
**Pull request by jamadden**
As used in persistent and zope.interface.

Unlike those, enable coverage conditionally, it's far too slow to always run (builds go from a minute to 6 minutes).

Adds Python 3.9 and aarch64 wheels.

### CODE REVIEW

**Review by icemac — APPROVED** [review]
Looks okay for me from reading the diff.

**Comment by jamadden** [comment]
Thanks for taking a look.

**Comment by jamadden** [comment]
Could someone with access to the `zope.wheelbuilder` PyPI account please add an appropriate PyPI token as the `TWINE_PASSWORD` repository secret in this repository?

**Comment by mgedmin** [comment]
Secret added.

**Comment by jamadden** [comment]
Thank you!

**Pull request merged**
