### PR TITLE
Don't use/poison global wheel cache when building w/ PURE_PYTHON.

### PR DESCRIPTION
**Pull request by tseaver**

### CODE REVIEW

**Comment by jamadden** [comment]
LGTM.

**Comment by tseaver** [comment]
I will merge after Travis passes.  The appveyor failures are expected until we land #30.

**Comment by jamadden** [comment]
Travis runs 'python setup.py test' so it isn't testing tox.ini AFAICS.

**Comment by tseaver** [comment]
D'oh, should've realized.

**Comment by mgedmin** [comment]
I've found a setting called "Skip branches without appveyor.yml" and enabled it.  (Ought to be default IMHO, but I can see why AppVeyor decided otherwise.)

**Pull request merged**
