### PR TITLE
Node sizes

### PR DESCRIPTION
**Pull request by jimfulton**
This is an alternative to the feature.configure_tree_bucket_sizes branch for controlling node sizes.

You control maximum node sizes by subclassing a BTree class and overriding max_internal_size and/or max_leaf_size.

### CODE REVIEW

**Comment by jimfulton** [comment]
WRT increasing default sizes:

+1 :) How much?

No evolution of existing data is needed.

**Comment by Krilivye** [comment]
Suggestion for defining how much:

Look at size of lot of existing production BTree => mean it.
:)
:+1:

**Comment by jimfulton** [comment]
Did you just volunteer to come back with a recommendation? :)

**Comment by Krilivye** [comment]
Rule of thumb in our team looks like "Correct" Large BTree should be no more than 100K.
Else start rework on data design. This is in the current default configuration. (250Max/buckets of 30).
I will benchmark different size next week :)

**Pull request merged**
