### PR TITLE
attempt to fix pypi password

### PR DESCRIPTION
**Pull request by fgregg**

### CODE REVIEW

**Comment by fgregg** [comment]
Hi @tseaver, this PR attempts to fix the PYPIPASSWORD setting for travis deploying the Mac OS X wheels to pypi. If you merge this into master and push another tag, hopefully it will work.

**Comment by tseaver** [comment]
Fingers crossed:  https://pypi.python.org/pypi/BTrees/4.3.1

**Comment by fgregg** [comment]
As a heads up, the appveyor builds are going to appear to fail, because they will not be able to upload a release to pypi with the same name as release already on pypi.

**Comment by tseaver** [comment]
The name of the wheel built by Appveyor shouldn't match (or is it trying to build the `sdist`, too?)

**Comment by fgregg** [comment]
oh, you bumped the versions! Nevermind!

**Comment by fgregg** [comment]
Whoop! Mac OS X wheels are up!

**Comment by tseaver** [comment]
Hmm, we don't build `py34` wheels?

**Comment by fgregg** [comment]
I can add it.

**Comment by tseaver** [comment]
W00t!  we have Windows and OS/X wheels.

**Pull request merged**
