### PR TITLE
Blacked the code

### PR DESCRIPTION
**Pull request by azmeuk**
I used [black](https://github.com/psf/black) to format the code.
I really like the code that blacks produces, and my stylecheckers too :), however I would understand if you think this is too much noise on the git history.

### CODE REVIEW

**Comment by freddrake** [comment]
Perhaps I've missed it, but has there been a discussion about whether a tool like Black should be used on the zopefoundation repositories?  This feels like something that should be decided at a larger scale, especially given that there would be enormous churn.

The benefits should be well understood and the value agreed upon by active maintainers across the community.

@jamadden?  @mgedmin?

**Comment by jugmac00** [comment]
There was a decision against the usage of black - for now.

https://github.com/zopefoundation/meta/issues/6

**Comment by freddrake** [comment]
Closing this PR.

@azmeuk: Thank you for your interest in contributing!

**Comment by azmeuk** [comment]
I totally understand!

**Pull request closed without merging**
